name: medisee
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.7=h166bdaf_0
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.10.6=ha86cf86_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022f=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==2.1.0
    - accelerate==1.2.0
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - aiosignal==1.3.1
    - altair==5.5.0
    - annotated-types==0.7.0
    - anyio==4.7.0
    - async-timeout==5.0.1
    - attrs==24.2.0
    - bitsandbytes==0.41.1
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - contourpy==1.3.1
    - cycler==0.12.1
    - deepspeed==0.16.2
    - einops==0.4.1
    - exceptiongroup==1.2.2
    - fastapi==0.115.6
    - ffmpy==0.4.0
    - filelock==3.16.1
    - flash-attn==2.3.5
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2024.10.0
    - gradio==5.9.1
    - gradio_client==1.5.2
    - grpcio==1.68.1
    - h11==0.14.0
    - hjson==3.1.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.27.0
    - idna==3.10
    - imageio==2.36.1
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.7
    - lazy_loader==0.4
    - linkify-it-py==2.0.3
    - markdown==3.7
    - markdown-it-py==2.2.0
    - markdown2==2.4.10
    - markupsafe==2.1.5
    - matplotlib==3.9.3
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - msgpack==1.1.0
    - multidict==6.1.0
    - multiscaledeformableattention==1.0
    - narwhals==1.17.0
    - networkx==3.4.2
    - ninja==1.11.1.3
    - numpy==1.24.2
    - nvidia-ml-py==12.560.30
    - openai==0.27.8
    - opencv-python==4.8.0.74
    - orjson==3.10.12
    - packaging==24.2
    - pandas==2.2.3
    - peft==0.4.0
    - pillow==11.0.0
    - propcache==0.2.1
    - protobuf==5.29.1
    - psutil==6.1.0
    - py-cpuinfo==9.0.0
    - pycocotools==2.0.6
    - pydantic==2.10.3
    - pydantic_core==2.27.1
    - pydub==0.25.1
    - pygments==2.18.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.19
    - pytz==2024.2
    - pyyaml==6.0.2
    - ray==2.6.1
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.31.0
    - rich==13.9.4
    - rpds-py==0.22.3
    - ruff==0.8.3
    - safehttpx==0.1.6
    - safetensors==0.4.5
    - scikit-image==0.25.0
    - scipy==1.11.2
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - shortuuid==1.0.11
    - six==1.17.0
    - sniffio==1.3.1
    - starlette==0.41.3
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tifffile==2024.12.12
    - tokenizers==0.21.0
    - tomlkit==0.13.2
    - torch==1.13.1+cu117
    - torchaudio==0.13.1+cu117
    - torchvision==0.14.1+cu117
    - tqdm==4.64.1
    - transformers==4.47.1
    - typer==0.15.1
    - typing_extensions==4.12.2
    - uc-micro-py==1.0.3
    - urllib3==2.2.3
    - uvicorn==0.23.2
    - websockets==11.0.3
    - werkzeug==3.1.3
    - wordcloud==1.9.4
    - yarl==1.18.3
prefix: 

